### ISSUE TITLE
"Invalid address" toast if internet off on device start

### ISSUE THREAD

**Issue by opusforlife2** [meshenger-app/meshenger-android#104]
If Meshenger is set to start upon boot, it shows this toast if there is no internet access. It should wait for internet to be turned on before validating the device address.

**Comment by mwarning** [comment]
I am not sure where the message comes from. Does it say `invalid address` or  `Invalid Address`? This could happen when the address validation fails when the database is loaded. But this would not be limited to the start at bootup.

**Comment by mwarning** [comment]
This error would come if the address entry for a contact is invalid. Maybe the address entry contains an invalid character?
It should match `^[0-9a-fA-F]{2}(:[0-9a-fA-F]{2}){5}$`. You can also create a backup and look at the JSON.

**Comment by mwarning** [comment]
hm, that error message should have been shown when you tried to add the contact via QR code. No idea what is wrong.
Can you check if the address looks valid when you look at the json data?

**Comment by mwarning** [comment]
Then I have no idea what is going on there :D

**Comment by mwarning** [comment]
I would tend to close this issue and wait for the next time it appears.

Does the error still appear when you export a backup and then import it into a freah installation?
In that case it would be helpful if you could send we the backup json file (without the private key).
I could then try to reproduce the error on my side.

**Comment by mwarning** [comment]
That  sounds like a good idea.

**Comment by mwarning** [comment]
Let me know what you find out. If we can find the bug, the fix can go into the next release.

**Comment by mwarning** [comment]
> Further investigation done. You were right about the bug being with the contact addresses!
> 
> Apparently, Meshenger stores the MAC address of the contact after a QR scan. But one of my devices (Alice) has MAC randomisation. So the address stored in Meshenger's database on the other device (Bob) is permanently wrong after a while. (I checked the backup JSON.)

Yes, this is a problem / limitation of Meshenger. But it should be possible  to disable MAC address randomization for an SSID (tested on Android 10). But then Android tends to assign itself an fe80 address that does not contain address.
So the DHCP server needs to assign the phone an address that contains that MAC address. This is not a wifi router configuration you encounter ofter. It is common for community Mesh networks (like Freifunk). Then the phones IP address will always be the same.


> 
> This doesn't seem to bother Meshenger on Bob if Wifi on Bob is on. But if it's off, the app refuses to start (it opens and then immediately minimises back into the icon), and shows the error toast (which I can confirm shows Alice's old MAC address because it matches the JSON!) each time. This is 100% reproducible.

That really sounds like a bug. I would like to reproduce it. Can you maybe show me a backup (without any data you care about). I would try to import it as backup.

> 
> So the bug, I think, is that the presence or absence of Wifi can somehow cause Meshenger to error out due to the old/incorrect MAC address.

> 
> Secondly, Bob seems to be able to discover Alice (sometimes it takes a few tries) despite the incorrect stored MAC address. But it doesn't update that address in the database for some reason. (I took another JSON backup after ensuring I could call Alice from Bob.)

If the discovery works, then at least one address in the contact works.

> 
> And finally, since MAC randomisation is going to be ubiquitous going forward, maybe the devices should have some other way of discovering and ID'ing each other instead?

Well, the only other solutions would be:
1. implement a discovery mechanism, which does not work on mesh networks
2. tell the wifi router to assign fixed IP addresses to the phones
3. let the WiFi router add the hostname to the DHCP server, then you can add `<name-of-the-phone>.local` as address.
 
> 
> Also listing some other stuff I found that may or may not be bugs. If they are, I can open separate issues:
> 
>     1. Upon every device restart, Meshenger rapidly shows up and then returns to the homescreen (I'm assuming this has something to do with Start on Boot). Trying to resume it via Recent Apps does nothing. It just stays there showing the app name and a red page. Can this be avoided? Other apps just directly start a permanent foreground notification. (This behaviour is what led me to mistakenly think the MAC address bug was about device restarts.)

Yes, this can be avoided by code refactoring and tinkering. I have choosen the easy way to do the start on boot.

> 
>     2. Cutting an ongoing call shows "Declined". That status should only show for rejected calls. This should say "Ended" instead. Or maybe "You ended the call"/"The other user ended the call" for more clarity.

Good idea. I will check how we can fix that.

> 
>     3. 'Push to talk' doesn't work initially. The mic icon shows up as if it's turned on at first. Holding it and talking does nothing. Instead, upon tapping it once, the mic icon changes to off (with a slash through it), and from then on, it can be held to talk.

You have found another bug.  :-)

> 
>     4. I sometimes see a red status dot despite the other device being online. Tapping the dot even says it's online, while staying red. (But this only happens on Bob, so let's see if this magically goes away after the main bug is fixed.)

This sounds like a display logic bug. Hm, no idea why that is happening. 4.1.7 allows you to update the status by send a ping from the contacts context menu. Maybe that will then turn it green.

> 
>     5. Sometimes, calling Alice from Bob causes an error. This occurs each time until I call Bob from Alice. Then calling Alice from Bob works fine too. (This, too, might be magically fixed.)

This might be due to some lost WiFi packet or shitty routing. In the end we would need to run tcpdump on a router to investigate.

**Comment by mwarning** [comment]
2 & 3 should be fixed now

**Comment by mwarning** [comment]
> > 4.1.7 allows you to update the status by send a ping from the contacts context menu.
> 
> Maybe the status could be refreshed automatically if the user is viewing their contact list? Like every 5 seconds? Or will that consume too much battery?
The battery is one issue. To refresh the contact list on viewing is an idea (it is already done to some extend).
I tend to make this configurable. Refresh automatically and refresh explicity (via contaext menu entry). 

> 
> > If the call works, then at least one address in the contact works.
> 
> The only address I can see in the JSON backup is the outdated one, though. I just took yet another backup to confirm. I'm not sure what's happening here. The call works even if the MAC-randomised device shows offline, too. Maybe the device is being identified by the private key instead? I can't think of any other reason.

The only reason the error can appears if the address is invalid.  Can you try to remove the address from the backup and check if the error is gone? Maybe the MAC address contains an ivalid character. Or it contains lower case characters (Meshenger is a bit picky about that).

> 
> > tell the wifi router to assign fixed IP addresses to the phones
> 
> Same privacy/security issue with fixed IP addresses, though.
> 
> > Well, the only other solutions would be:
> 
> Since 1 is non-viable as you say, 3 seems like the only option? Is this something that can be fully automated, or does it require manual configuration?
> 
> > I would like to reproduce it. Can you maybe show me a backup
> 
> Oh, do you not have a randomised device on hand? I have no idea how to sanitise the JSON backup.

**Comment by mwarning** [comment]
> > Refresh automatically and refresh explicity (via contaext menu entry).
> 
> I don't really understand the utility of per-contact refreshing, to be honest. I would have just gone for a universal Refresh icon in the top bar, or pull-to-refresh, which are likely to be more frequently used.

I see why it is confusing (the refresh happens when the Meshenger window is created, not when it is resumed)). This is already fixed in the source code.

> 
> > The only reason the error can appears if the address is invalid. Can you try to remove the address from the backup and check if the error is gone? Maybe the MAC address contains an ivalid character. Or it contains lower case characters (Meshenger is a bit picky about that).
> 
> Turns out, it's not even about the outdated addresses. Even the currently valid address causes the same error. So this has nothing to do with MAC randomisation after all. I don't know why I didn't think to test this before. Sorry.
> 
> Yes, removing the address caused the error to disappear. But I checked the JSON backup on the other device as well. The address is formatted exactly the same on both devices: `fe80::xxxx:xxxx:xxxx:xxxx%wlan0` (all characters in lowercase). Why does one device bug out while the other doesn't?

Are both devices using the same version? I assume that the address is two locations, once in the settings section and once in the contact section for the other device?

> 
> I thought to test after replacing all lowercase characters with uppercase ones, but editing the address manually just causes Meshenger to reject the import with a "invalid password" toast. Not sure why that happens.

That "invalid password" message might happen when the first character of the database is not a `{`.

**Comment by mwarning** [comment]
The address in the Address Management contains a MAC address, if any of the other IPV6 addresses contains it. Otherwise it does not make sense to use the MAC. In the end we need an IP adresss to communicate.
So if you configure Android to use a randomized MAC address for the WLAN device, then you will probably also have IPv6 addresses (fe80::* and others) that contain it.
If you configure Android to use the real hardware MAC address, then Android will *not* put it into IPv6 addresses by default (but community mesh networks might use that MAC and force Android to use an IP address with its MAC address in it, then the MAC address will appear in the address management list) .
It is a bit complicated, but that is probably one thing you are seeing.

Anyway, let's close this ticket and let's hope the error is fixed. :D

**Comment by mwarning** [comment]
ah, you are right. Fixed here: https://github.com/meshenger-app/meshenger-android/commit/23df170676a9ba20cf4927fecc7719b9a4210348
