### ISSUE TITLE
Mobile data IPs are not listed in addresses

### ISSUE THREAD

**Issue by iddq** [meshenger-app/meshenger-android#143]
Mobile data IPs are not listed in addresses

**Comment by mwarning** [comment]
Yes, this is intentional since they seem to be of no use. Mobile connections give you private IP addresses that you usually cannot use to connec to other mobile users (if I am not mistaken). You can only connect to a gateway.

If you want to experiment with them, then you can enter them manually in Meshenger.

**Comment by mwarning** [comment]
Let me know if you see a legimate use. Until then I like to close this ticket.

**Comment by mwarning** [comment]
@iddq OK, then let me see if I can reenable it.

**Comment by mwarning** [comment]
mobile data connection IPs will be available in the next release.

**Comment by mwarning** [comment]
fixed in 4.3.0

**Comment by iddq** [comment]
Thanks, Do you have to manually upload the APK for the updates in the stores?

**Comment by mwarning** [comment]
The new release will be automatically picked up by FDroid. It will appear there in ca. 3-7 days.
