### ISSUE TITLE
chat support

### ISSUE THREAD

**Issue by mwarning** [meshenger-app/meshenger-android#7]
This would be a major feature...

**Comment by wuniversales** [comment]
Great, it would be nice to be able to send files, audios, video messages, emoticons, to be able to create groups ...

**General idea: The administrators of the group would have some general adjustments for the group, according to the group configuration a category is assigned.**

Generic settings for group administrators:

Give the possibility that the users of the group, add new users, or not.
Allow users to send messages or not.
Allow users to send images or not.
Allow users to send files or not.
Allow users to send music or not.
Allow users to send audios or not.
Allow users to send gif or not.
Other settings...

Depending on the general settings of the group, categories could be assigned, the categories change according to the group's permissions.

**Category "Channels"**
Category feature:


Group members can only receive messages.


All users can create a new "Channel" by default group permissions shown above.


For example, in a group that is not allowed to speak to its members and only administrators can speak, this category would be assigned since information is only received from administrators (for example, offers, or news about games, news, etc.)
In this case it would be good to give the possibility of self-publishing rss news for administrators.

**Category "Group"**
Category feature:


Group members can send and receive messages.


Group members cannot add new users (Only administrators can do so)


All users can create a new "Group" by default group permissions shown above.


**Category "Supergroup"**
Category feature:


Group members can send and receive messages.


Group members can add new users.


All users can create a new "Supergroup" by default group permissions shown above.


I think that would be better.
More organized, cleaner.
Regards

**Comment by eatavegan** [comment]
Instead of reinventing the wheel have you considered instead linklocal xmpp?

https://xmpp.org/extensions/attic/xep-0174-0.14.html

> This document describes how to establish XMPP-like communications over local networks using zero-configuration networking.

**Comment by mwarning** [comment]
@wuniversales Let's keep things simple and focus on one-to-one text only messaging for now.

**Comment by wuniversales** [comment]
Yes, of course, for now yes, but in the future to know :)

**Comment by mwarning** [comment]
Since we have trouble to get the current feature working at all, let's put this in a feature list and not bother with a whole issue.
